# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanatci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilgilendigi_bolum', models.IntegerField(choices=[(1, 'Resim'), (2, 'Heykel'), (3, 'Muzik'), (4, 'Tiyatro')])),
                ('kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.Kisi')),
            ],
        ),
    ]
